### ISSUE TITLE
NoMethodError (undefined method `bytesize' for #<Log4r::GelfOutputter:0x000000041b09a0>):

### ISSUE THREAD

**Issue by solars** [wr0ngway/log4r-gelf#5]
Hey,

I'm getting this exception:

NoMethodError (undefined method `bytesize' for #<Log4r::GelfOutputter:0x000000041b09a0>):
  rack (1.5.2) lib/rack/utils.rb:335:in`bytesize'
  sinatra (1.4.3) lib/sinatra/base.rb:147:in `block in finish'
  sinatra (1.4.3) lib/sinatra/base.rb:147:in`each'
  sinatra (1.4.3) lib/sinatra/base.rb:147:in `inject'
  sinatra (1.4.3) lib/sinatra/base.rb:147:in`finish'
  sinatra (1.4.3) lib/sinatra/base.rb:893:in `call!'
  sinatra (1.4.3) lib/sinatra/base.rb:870:in`call'
  newrelic_rpm (3.6.8.164) lib/new_relic/rack/error_collector.rb:43:in `call'
  newrelic_rpm (3.6.8.164) lib/new_relic/rack/browser_monitoring.rb:16:in`call'
  newrelic_rpm (3.6.8.164) lib/new_relic/rack/agent_hooks.rb:22:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in`forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in`lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in`call'
  rack (1.5.2) lib/rack/nulllogger.rb:9:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in`call'
  sinatra (1.4.3) lib/sinatra/base.rb:175:in `call'
  sinatra (1.4.3) lib/sinatra/base.rb:1949:in`call'
  sinatra (1.4.3) lib/sinatra/base.rb:1449:in `block in call'
  sinatra (1.4.3) lib/sinatra/base.rb:1726:in`synchronize'
  sinatra (1.4.3) lib/sinatra/base.rb:1449:in `call'
  actionpack (4.0.0) lib/action_dispatch/journey/router.rb:71:in`block in call'
  actionpack (4.0.0) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.0.0) lib/action_dispatch/journey/router.rb:59:in`call'
  actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb:655:in `call'
  newrelic_rpm (3.6.8.164) lib/new_relic/rack/error_collector.rb:43:in`call'
  newrelic_rpm (3.6.8.164) lib/new_relic/rack/agent_hooks.rb:22:in `call'
  newrelic_rpm (3.6.8.164) lib/new_relic/rack/browser_monitoring.rb:16:in`call'
  rack-jsonp-middleware (0.0.9) lib/rack/jsonp.rb:24:in `call'

...

Does anyone know what this could be?

Versions are: Ruby 1.9.3, Rails 4, gelf (1.4.0), log4r-gelf (0.9.0)

Thanks a lot!
Christoph

**Comment by solars** [comment]
still getting this
